version: "3.3"

services:
  whoami:
    image: "containous/whoami"
    container_name: "simple_service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`${DOMAIN}`) && Path(`/whoami`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    networks:
      - web

networks:
  web:
    external: true
