version: '3'

services:
  traefik:
    image: traefik:1.7.14
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/traefik.toml:/traefik.toml
      - /opt/traefik/acme.json:/acme.json
    container_name: traefik
    networks:
      - web
  ghost:
    image: ghost:2.25
    restart: always
    networks:
      - web
    labels:
      - "traefik.enable=true"

networks:
  web:
    external: true
