version: '3.3'

services:
  traefik:
    image: traefik:2.0.1
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${TRAEFIK_CONFIG}/traefik.toml:/traefik.toml"
      - "${TRAEFIK_CONFIG}/dynamic-configuration/:/dynamic-configuration/"
      - "${VOLUMES_DIRECTORY:-/docker}/traefik/acme.json:/acme.json"
      - "${VOLUMES_DIRECTORY:-/docker}/logs/traefik/:/logs/"
    container_name: traefik
    networks:
      - web

networks:
  web:
    external: true
