version: '3.3'

services:
  traefik:
    image: traefik:2.0.1
    restart: always
    ports:
      - 80:80
      - 443:443
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=web"
      - "--providers.file=true"
      - "--providers.file.directory=/dynamic-configuration/"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
      - "--log=true"
      - "--log.filepath=/logs/traefik.log"
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--accesslog.filepath=/logs/access.log"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      #- "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=acme.json"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./dynamic-configuration/:/dynamic-configuration/:ro"
      - "${VOLUMES_DIRECTORY:-/docker}/traefik/acme.json:/acme.json"
      - "${VOLUMES_DIRECTORY:-/docker}/logs/traefik/:/logs/"
    container_name: traefik
    networks:
      - web

networks:
  web:
    external: true
