version: '3.3'

services:
  traefik:
    image: traefik:2.0.1
    restart: always
    ports:
      - 80:80
      - 443:443
    command:
      #- "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file=true"
      - "--providers.file.directory=/dynamic-configuration/"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
      - "--log==true"
      - "--log.filepath=/logs/traefik.log"
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--accesslog.filepath=/logs/access.log"
      - "--certificatesresolvers.tlschallenge.acme.tlschallenge=true"
      #- "--certificatesresolvers.mytlschallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.tlschallenge.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.tlschallenge.acme.storage=/acme.json"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${TRAEFIK_CONFIG}/dynamic-configuration/:/dynamic-configuration/"
      - "${VOLUMES_DIRECTORY:-/docker}/traefik/acme.json:/acme.json"
      - "${VOLUMES_DIRECTORY:-/docker}/logs/traefik/:/logs/"
    container_name: traefik
    networks:
      - web

networks:
  web:
    external: true
