version: '3.3'

services:
  http-service:
    image: nginx:1.17
    volumes:
      - "./content:/usr/share/nginx/html:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hsts.rule=PathPrefix(`/`)"
      - "traefik.http.routers.hsts.middlewares=sts-middleware@file"
      - "traefik.http.routers.ghost.entrypoints=web"

    networks:
      - web

networks:
  web:
    external: true

