[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false

[providers.file]
  directory = "/dynamic-configuration/"
  watch = true

[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.web-secure]
    address = ":443"

[log]
  filePath = "/logs/traefik.log"
  level = "DEBUG"

[accessLog]
  filePath = "/logs/access.log"

[certificatesResolvers]
  [certificatesResolvers.tls-resolver]
    [certificatesResolvers.tls-resolver.acme]
      tlschallenge = true
      #caserver="https://acme-staging-v02.api.letsencrypt.org/directory"
      email= "email@domain.com"
      storage="/acme.json"
